/**
 * The query language: kernel (`Q`), constructor and composition (`Query`),
 * the fluent app spelling (`Query.from`), and the pipeable stdlib. One
 * kind of object — every query is a rule — with two advanced spellings
 * (pipe, generator) under the fluent chain.
 */

export {
  Q,
  isVar,
  isValueSpec,
  mkVar,
  runBody,
  type AnyCommand,
  type AnyVar,
  type AttrLike,
  type BClause,
  type BuildCtx,
  type Cell,
  type CellRecord,
  type DistinctSpec,
  type FactHandle,
  type Fragment,
  type Projection,
  type PullSpec,
  type QueryGen,
  type RowOfProjection,
  type RowsSpec,
  type ValueSpec,
  type Var,
} from "./kernel.ts";

export { decodeCursor, encodeCursor } from "./cursor.ts";
export {
  enrich,
  isCursor,
  isPipeline,
  isQueryObject,
  isRuleValue,
  lowerQueryAst,
  lowerQueryObject,
  tryLowerQueryObject,
  q,
  refine,
  rule,
  symbolicIdentityLowering,
  type AnyQueryObject,
  type Cursor,
  type LoweredKernelQuery,
  type OpenResult,
  type Page,
  type Pipeline,
  type PipeStage,
  type QueryBody,
  type QueryObject,
  type QueryOrder,
  type QueryOrderKey,
  type Row,
  type Rows,
  type RuleValue,
  type SelectExtra,
} from "./query.ts";

export { from } from "./fluent.ts";
export type { EntityRow, FluentQuery, RefIdCell, WhereEq } from "./fluent.ts";

export {
  any,
  assertedBy,
  backlink,
  byId,
  entities,
  every,
  follow,
  gt,
  gte,
  has,
  ids,
  includes,
  is,
  limit,
  lt,
  lte,
  matching,
  missing,
  none,
  not,
  offset,
  orderBy,
  select,
  some,
  stage,
  startsWith,
  updatedSince,
  type FilterStage,
  type FollowStage,
  type HatchIdRow,
  type IdRow,
  type ReverseFilter,
  type TraversalStage,
} from "./lib.ts";
