/**
 * Compiled `RAMOSE_POLICY` JSON for the SPA overlay. `policy.ts` is the
 * source of truth (`compiledPolicy()`); this file is the browser-safe
 * wire so first paint does not import the deploy-time compiler.
 *
 * `examples/reef/test/policy.test.ts` asserts they stay in step.
 */
export const policyWire =
  '{"version":1,"principal":":user/sub","classes":["admin","member","viewer"],"attrs":{":issue/privateNote":{"read":[{"_tag":"allow","expr":{"_tag":"class","class":"admin"}}]}},"ns":{"user":{"read":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"},{"_tag":"class","class":"viewer"}]}}],"create":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"}]}}]},"label":{"read":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"},{"_tag":"class","class":"viewer"}]}}],"create":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"}]}}]},"issue":{"read":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"},{"_tag":"class","class":"viewer"}]}}],"add":[{"_tag":"allow","expr":{"_tag":"and","exprs":[{"_tag":"class","class":"member"},{"_tag":"eq","attr":":issue/creator","operand":{"_tag":"principal"}}]}}],"retract":[{"_tag":"allow","expr":{"_tag":"and","exprs":[{"_tag":"class","class":"member"},{"_tag":"eq","attr":":issue/creator","operand":{"_tag":"principal"}}]}}],"retractEntity":[{"_tag":"allow","expr":{"_tag":"and","exprs":[{"_tag":"class","class":"member"},{"_tag":"eq","attr":":issue/creator","operand":{"_tag":"principal"}}]}}],"create":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"}]}}]},"comment":{"read":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"},{"_tag":"class","class":"viewer"}]}}],"retract":[{"_tag":"allow","expr":{"_tag":"and","exprs":[{"_tag":"class","class":"member"},{"_tag":"eq","attr":":comment/author","operand":{"_tag":"principal"}}]}}],"retractEntity":[{"_tag":"allow","expr":{"_tag":"and","exprs":[{"_tag":"class","class":"member"},{"_tag":"eq","attr":":comment/author","operand":{"_tag":"principal"}}]}}],"create":[{"_tag":"allow","expr":{"_tag":"or","exprs":[{"_tag":"class","class":"admin"},{"_tag":"class","class":"member"}]}}]}},"preset":{":user/sub":{"_tag":"claim","path":["sub"]},":issue/creator":{"_tag":"principal"},":comment/author":{"_tag":"principal"}}}';
